name: publish
on:
  push:
    branches:
      - master
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Container
      run: |-
            docker build . --tag ghcr.io/unclepaul84/twin-rinks-attendance-bot/tr_bot_demo:latest
            docker push ghcr.io/unclepaul84/twin-rinks-attendance-bot/tr_bot_demo:latest
